/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_project_dev_wirelessjoystick_desktop_nativecode_VirtualEvent */

#ifndef _Included_com_project_dev_wirelessjoystick_desktop_nativecode_VirtualEvent
#define _Included_com_project_dev_wirelessjoystick_desktop_nativecode_VirtualEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_project_dev_wirelessjoystick_desktop_nativecode_VirtualEvent
 * Method:    runVirtualKeyEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_project_dev_wirelessjoystick_desktop_nativecode_VirtualEvent_runVirtualKeyEvent
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_project_dev_wirelessjoystick_desktop_nativecode_VirtualEvent
 * Method:    runVirtualMouseClicEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_project_dev_wirelessjoystick_desktop_nativecode_VirtualEvent_runVirtualMouseClicEvent
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_project_dev_wirelessjoystick_desktop_nativecode_VirtualEvent
 * Method:    runVirtualMouseMoveEvent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_project_dev_wirelessjoystick_desktop_nativecode_VirtualEvent_runVirtualMouseMoveEvent
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
